URL_SERVICE = "https://fb4a74c9-ed28-4f61-b4a6-81bf62147e05.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
USERS_KITS_PATH = "/api/v1/kits"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_KITS_PATH = "/api/v1/kits/"